### ISSUE TITLE
[feat] 최초 프로젝트 세팅

### ISSUE THREAD

**Issue by i-colours-u** [TEAM-README/Readme-iOS#1]
## 📌  Feature Issue
프로젝트에 필요한 것들을 세팅합니다!

## 📝  To-do
- [x] Podfile 세팅하기
- [x] Fastlane 세팅하기
- [x] slack 연동하기
- [x] 프로젝트 폴더링 하기
- [x] 브랜치 미리 구분하기
- [x] 필요한 util들 채워놓기
