### ISSUE TITLE
[feat] Write 뷰 만들기

### ISSUE THREAD

**Issue by yangsubinn** [TEAM-README/Readme-iOS#14]
## 📌  Feature Issue
<img width="634" alt="스크린샷 2022-04-19 오후 2 05 34" src="https://user-images.githubusercontent.com/81167570/163923874-584d5e94-415f-4426-8c4d-5a3046ad666f.png">

## 📝  To-do
- [x]  기본 ui, layout 세팅
- [x]  플로우에 따라 ui, layout 분리
- [x]  textView 처리
- [x]  화면전환, 인터렉션 구현
