### ISSUE TITLE
[feat] 테스트 플라이트용 만들기

### ISSUE THREAD

**Issue by i-colours-u** [TEAM-README/Readme-iOS#36]
## 📌  Feature Issue
테플 올릴 정도의 사이즈로 작업을 진행합니다.
## 📝  To-do
- [x] 메인 아이콘 추가
- [x] 메인에서 스와이프 했을 때, Splash로 가지 않도록 처리
- [x] 쓰기 완료했을 때, 글 나타나게?
- [x] 약관, 문의하기 링크 추가하기
