### ISSUE TITLE
[fix] 글 작성 플로우 수정

### ISSUE THREAD

**Issue by yangsubinn** [TEAM-README/Readme-iOS#63]
## 📝  To-do
- [x] 프로그래스 바 레이아웃 수정
- [x] 텍스트필드 없는 텍스트 없는 경우 버튼 막기
- [x] 글 작성 플로우 마지막, '피드', '마이페이지' 볼드처리
